export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_INIT = 'REGISTER_USER_INIT';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER  = 'LOGIN_USER';
export const LOGIN_USER_INIT = 'LOGIN_USER_INIT';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const ENTRIES_REQUEST  = 'ENTRIES_REQUEST';
export const ENTRIES_REQUEST_INIT = 'ENTRIES_REQUEST_INIT';
export const ENTRIES_REQUEST_SUCCESS = 'ENTRIES_REQUEST_SUCCESS';
export const ENTRIES_REQUEST_ERROR = 'ENTRIES_REQUEST_ERROR';
